**Question 1**

In [ ]:
import numpy as np
arr = np.arange(1,11)
print("Array:",arr)
print("Shape:",arr.shape)
print("Data Type:",arr.dtype)
print("Sum of Elements:",arr.sum())
print("Mean of Elements:",arr.mean())
print("Max Value:",arr.max())
print("Min Value:",arr.min())

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data Type: int64
Sum of Elements: 55
Mean of Elements: 5.5
Max Value: 10
Min Value: 1


**Question 2**

In [ ]:
import numpy as np
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B=np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1],
])
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

print("\nMatrix Addition:")
print(A+B)

print("\nMatrix Subtraction:")
print(A-B)

print("\nElemnt wise Multiplication:")
print(A*B)

print("\nMatrix Multiplication:")
print(np.dot(A,B))

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Elemnt wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


**Question 3**

In [ ]:
import numpy as np
mark=np.array([
    [85,90,88,92],
    [70,65,72,68],
    [95,91,93,96],
    [60,75,70,80],
    [88,84,86,90]
])
stavg=np.mean(mark,axis=1)
print("Average marks of each student: ")
print(stavg)

sbavg=np.mean(mark,axis=0)
print("\nAverage marks of each subject: ")
print(sbavg)

print("\nHighest mark:",np.max(mark))
print("Lowest mark:",np.min(mark))

total=np.sum(mark,axis=1)
print("\nTotal marks of each student: ")
print(total)

high=np.argmax(total)
print("Student with highest total: Student:",high+1)

Average marks of each student: 
[88.75 68.75 93.75 71.25 87.  ]

Average marks of each subject: 
[79.6 81.  81.8 85.2]

Highest mark: 96
Lowest mark: 60

Total marks of each student: 
[355 275 375 285 348]
Student with highest total: Student: 3


**Question 4**

In [ ]:
import numpy as np
image=np.array([
    [100,120,130],
    [150,180,200],
    [50,80,100]
])
normalized=image/255
print("Original Image:")
print(image)

print("\nNormalized Image:")
print(normalized)

bright=image+30
print("\nImage with Brightness increased by 30:")
print(bright)

clipimg=np.clip(bright,0,255)
print("Clipped")
print(clipimg)

avgintensity=np.mean(clipimg)
print("\nAverage Pixel Intensity:",avgintensity)

Original Image:
[[100 120 130]
 [150 180 200]
 [ 50  80 100]]

Normalized Image:
[[0.39215686 0.47058824 0.50980392]
 [0.58823529 0.70588235 0.78431373]
 [0.19607843 0.31372549 0.39215686]]

Image with Brightness increased by 30:
[[130 150 160]
 [180 210 230]
 [ 80 110 130]]
Clipped
[[130 150 160]
 [180 210 230]
 [ 80 110 130]]

Average Pixel Intensity: 153.33333333333334


**Question 5**

In [ ]:
import numpy as np
sales=np.array([
    [120,130,140,150,160,170],
    [100,110,120,130,140,150],
    [150,145,160,170,180,190],
    [90,100,110,120,130,140]
])
total=np.sum(sales,axis=1)
print("Total sales of each product:")
print(total)

avgsales=np.mean(sales,axis=1)
print("\nAverage monthly sales of each product:")
print(avgsales)

best=np.argmax(total)
print("\nBest-selling product: Product",best+1)

monthtot=np.sum(sales,axis=0)
print("\nTotal sales of each month:")
print(monthtot)

bestmonth=np.argmax(monthtot)
print("Month with highest ovearll sales: Month:",bestmonth+1)

sd=np.std(sales,axis=1)
print("\nStandard deviation of sales of each product:")
print(sd)

Total sales of each product:
[870 750 995 690]

Average monthly sales of each product:
[145.         125.         165.83333333 115.        ]

Best-selling product: Product 3

Total sales of each month:
[460 485 530 570 610 650]
Month with highest ovearll sales: Month: 6

Standard deviation of sales of each product:
[17.07825128 17.07825128 15.92081098 17.07825128]
