# Question 1

In [ ]:
import pandas as pd

#Series
s = pd.Series(range(1, 11))

#Series into DataFrame
df = s.to_frame(name="Numbers")

print("Series:")
print(s)

print("\nDataFrame:")
print(df)

print("\nShape:", df.shape)
print("Data type:", s.dtype)
print("Sum:", s.sum())
print("Mean:", s.mean())
print("Maximum:", s.max())
print("Minimum:", s.min())

Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

DataFrame:
   Numbers
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

Shape: (10, 1)
Data type: int64
Sum: 55
Mean: 5.5
Maximum: 10
Minimum: 1


# Question 2

In [ ]:
import pandas as pd
rows = ["R1", "R2", "R3"]
columns = ["C1", "C2", "C3"]
A = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    index=rows,
    columns=columns
)
B = pd.DataFrame(
    [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]],
    index=rows,
    columns=columns
)

print("DataFrame A:")
print(A)
print("\nDataFrame B:")
print(B)

print("\nAddition:")
print(A + B)
print("\nSubtraction:")
print(A - B)
print("\nElement-wise Multiplication:")
print(A * B)
print("\nMatrix Multiplication:")
print(A.values.dot(B.values))

DataFrame A:
    C1  C2  C3
R1   1   2   3
R2   4   5   6
R3   7   8   9

DataFrame B:
    C1  C2  C3
R1   9   8   7
R2   6   5   4
R3   3   2   1

Addition:
    C1  C2  C3
R1  10  10  10
R2  10  10  10
R3  10  10  10

Subtraction:
    C1  C2  C3
R1  -8  -6  -4
R2  -2   0   2
R3   4   6   8

Element-wise Multiplication:
    C1  C2  C3
R1   9  16  21
R2  24  25  24
R3  21  16   9

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Question 3

In [ ]:
import pandas as pd

data = {
    "Student": ["Amit", "Bhavna", "Chirag", "Divya", "Esha"],
    "Maths": [85, 70, 95, 60, 88],
    "Science": [90, 65, 91, 75, 84],
    "English": [88, 72, 93, 70, 86],
    "History": [92, 68, 96, 80, 90]
}
df = pd.DataFrame(data)

df.set_index("Student", inplace=True)
df["Total"] = df.sum(axis=1)

df["Average"] = df[["Maths", "Science", "English", "History"]].mean(axis=1)

print("Student Data:")
print(df)

print("\nAverage marks of each student:")
print(df["Average"])

print("\nAverage marks of each subject:")
print(df[["Maths", "Science", "English", "History"]].mean())

print("\nHighest mark:")
print(df[["Maths", "Science", "English", "History"]].max().max())

print("\nLowest mark:")
print(df[["Maths", "Science", "English", "History"]].min().min())

print("\nStudent with highest total marks:")
print(df["Total"].idxmax())

print("\nSorted by Total Marks:")
print(df.sort_values(by="Total", ascending=False))

Student Data:
         Maths  Science  English  History  Total  Average
Student                                                  
Amit        85       90       88       92    355    88.75
Bhavna      70       65       72       68    275    68.75
Chirag      95       91       93       96    375    93.75
Divya       60       75       70       80    285    71.25
Esha        88       84       86       90    348    87.00

Average marks of each student:
Student
Amit      88.75
Bhavna    68.75
Chirag    93.75
Divya     71.25
Esha      87.00
Name: Average, dtype: float64

Average marks of each subject:
Maths      79.6
Science    81.0
English    81.8
History    85.2
dtype: float64

Highest mark:
96

Lowest mark:
60

Student with highest total marks:
Chirag

Sorted by Total Marks:
         Maths  Science  English  History  Total  Average
Student                                                  
Chirag      95       91       93       96    375    93.75
Amit        85       90       88       92   

# Question 4

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Day": ["Day1", "Day2", "Day3", "Day4",
            "Day5", "Day6", "Day7"],
    "Temperature": [30, np.nan, 32, 29, np.nan, 35, 31]
})

print("Original DataFrame:")
print(df)

print("\nMissing values:")
print(df.isnull())

mean_temp = df["Temperature"].mean()
print("\nMean Temperature:", mean_temp)

df_mean = df.copy()
df_mean["Temperature"] = df_mean["Temperature"].fillna(mean_temp)

print("\nAfter filling with mean:")
print(df_mean)

df_ffill = df.copy()
df_ffill["Temperature"] = df_ffill["Temperature"].ffill()

print("\nAfter Forward Fill:")
print(df_ffill)

df_drop = df.dropna()

print("\nAfter dropping missing rows:")
print(df_drop)

print("\nAverage temperature after cleaning:",
      df_drop["Temperature"].mean())

Original DataFrame:
    Day  Temperature
0  Day1         30.0
1  Day2          NaN
2  Day3         32.0
3  Day4         29.0
4  Day5          NaN
5  Day6         35.0
6  Day7         31.0

Missing values:
     Day  Temperature
0  False        False
1  False         True
2  False        False
3  False        False
4  False         True
5  False        False
6  False        False

Mean Temperature: 31.4

After filling with mean:
    Day  Temperature
0  Day1         30.0
1  Day2         31.4
2  Day3         32.0
3  Day4         29.0
4  Day5         31.4
5  Day6         35.0
6  Day7         31.0

After Forward Fill:
    Day  Temperature
0  Day1         30.0
1  Day2         30.0
2  Day3         32.0
3  Day4         29.0
4  Day5         29.0
5  Day6         35.0
6  Day7         31.0

After dropping missing rows:
    Day  Temperature
0  Day1         30.0
2  Day3         32.0
3  Day4         29.0
5  Day6         35.0
6  Day7         31.0

Average temperature after cleaning: 31.4


# Question 5

In [ ]:
import pandas as pd

data = {
    "Product": ["Product A", "Product B", "Product C", "Product D"],
    "Jan": [120, 100, 150, 90],
    "Feb": [130, 110, 145, 100],
    "Mar": [140, 120, 160, 110],
    "Apr": [150, 130, 170, 120],
    "May": [160, 140, 180, 130],
    "Jun": [170, 150, 190, 140]
}
df = pd.DataFrame(data)

df.set_index("Product", inplace=True)
print("Sales Data:")
print(df)

total_sales = df.sum(axis=1)
print("\nTotal sales of each product:")
print(total_sales)

average_sales = df.mean(axis=1)
print("\nAverage monthly sales:")
print(average_sales)

best_product = total_sales.idxmax()
print("\nBest-selling product:")
print(best_product)

monthly_total = df.sum(axis=0)
best_month = monthly_total.idxmax()
print("\nMonth with highest overall sales:")
print(best_month)

std_sales = df.std(axis=1)
print("\nStandard deviation:")
print(std_sales)

df["Q1"] = df[["Jan", "Feb", "Mar"]].sum(axis=1)
df["Q2"] = df[["Apr", "May", "Jun"]].sum(axis=1)
pivot_table = df[["Q1", "Q2"]]

print("\nQuarterly Sales Pivot Table:")
print(pivot_table)

Sales Data:
           Jan  Feb  Mar  Apr  May  Jun
Product                                
Product A  120  130  140  150  160  170
Product B  100  110  120  130  140  150
Product C  150  145  160  170  180  190
Product D   90  100  110  120  130  140

Total sales of each product:
Product
Product A    870
Product B    750
Product C    995
Product D    690
dtype: int64

Average monthly sales:
Product
Product A    145.000000
Product B    125.000000
Product C    165.833333
Product D    115.000000
dtype: float64

Best-selling product:
Product C

Month with highest overall sales:
Jun

Standard deviation:
Product
Product A    18.708287
Product B    18.708287
Product C    17.440375
Product D    18.708287
dtype: float64

Quarterly Sales Pivot Table:
            Q1   Q2
Product            
Product A  390  480
Product B  330  420
Product C  455  540
Product D  300  390
